version: "2"

services:

    web:
        image: tutum/apache-php
        restart: always
        volumes:
            - ./htdocs:/app
            - ./tmp/logs-apache:/var/log/apache2
        ports:
            - ${WEB_PORT}:80
        environment:
            - ALLOW_OVERRIDE=true


    db:
        image: mariadb
        restart: always
        volumes:
            - ./tmp/mysql:/var/lib/mysql
#        ports:
#            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}

    pma:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - ${PMA_PORT}:80
        environment:
            MYSQL_DB_SERVER: db
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}

# not needed because automatically creating network
# beatween web, db, phpmyadmin
#        links:
#            - db

# throw ports needs for outside apps
# like nginx-reverse-proxy (if it don't use that network)
# or for db-manager
