version: '3'

services:
    web:
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./www:/var/www
            - ./tmp/logs:/var/log/nginx
        ports:
            - ${WEB_PORT}:80
        # links:
        #     - php

    php:
        build: ./php-fpm
        restart: always
        volumes:
            - ./www:/var/www
        # links:
        #     - db

    # web:
    #     image: tutum/apache-php
    #     restart: always
    #     volumes:
    #         - ./www:/app
    #         - ./tmp/logs-apache:/var/log/apache2
    #     ports:
    #         - ${WEB_PORT}:80
    #     environment:
    #         - ALLOW_OVERRIDE=true

    db:
        image: mariadb
        restart: always
        volumes:
            - ./tmp/mysql:/var/lib/mysql
#        ports:
#            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}

    pma:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - ${PMA_PORT}:80
        environment:
            MYSQL_DB_SERVER: db
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}

# not needed because automatically creating network
# beatween web, db, phpmyadmin
#        links:
#            - db

# throw ports needs for outside apps
# like nginx-reverse-proxy (if it don't use that network)
# or like Sequel Pro (db manager)
