version: '3'

services:
    web:
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./www:/var/www
            - ./tmp/logs:/var/log/nginx
        ports:
            - ${WEB_EXT_PORT}:80
        # links:
        #     - php
        environment:
            VIRTUAL_HOST: ${WEB_VIRTUAL_HOST}
            VIRTUAL_PORT: ${WEB_VIRTUAL_PORT}
            LETSENCRYPT_HOST: ${WEB_LETSENCRYPT_HOST}
            LETSENCRYPT_EMAIL: ${WEB_LETSENCRYPT_EMAIL}

    php:
        build: ./php-fpm
        restart: always
        volumes:
            - ./www:/var/www
        # links:
        #     - db
        environment:
            SITE_NAME: ${SITE_NAME}
            SITE_URL: ${SITE_URL}
            SITE_DEBUG: ${SITE_DEBUG}

            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_USER_LOGIN: ${DB_USER_LOGIN}
            DB_USER_PASSWD: ${DB_USER_PASSWD}
            DB_NAME: ${DB_NAME}
            DB_BACKUP_FILE: ${DB_BACKUP_FILE}
    db:
        image: mariadb:latest
        restart: always
        volumes:
            - ./tmp/mysql:/var/lib/mysql
        ports:
            - ${DB_EXT_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
            MYSQL_USER: ${DB_USER_LOGIN}
            MYSQL_PASSWORD: ${DB_USER_PASSWD}
            MYSQL_DATABASE: ${DB_NAME}

    pma:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - ${PMA_EXT_PORT}:80
        environment:
            MYSQL_DB_SERVER: ${DB_HOST}
            MYSQL_USER: ${DB_USER_LOGIN}
            MYSQL_PASSWORD: ${DB_USER_PASSWD}
            MYSQL_DATABASE: ${DB_NAME}

            VIRTUAL_HOST: ${PMA_VIRTUAL_HOST}
            VIRTUAL_PORT: ${PMA_VIRTUAL_PORT}
            LETSENCRYPT_HOST: ${PMA_LETSENCRYPT_HOST}
            LETSENCRYPT_EMAIL: ${PMA_LETSENCRYPT_EMAIL}

# not needed because automatically creating network
# beatween web, db, phpmyadmin
#        links:
#            - db

# throw ports needs for outside apps
# like nginx-reverse-proxy (if it don't use that network)
# or like Sequel Pro (db manager)

networks:
    default:
        external:
            name: ${NETWORK:-webproxy}
