version: '3'
services:
  web:
    image: tutum/apache-php
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "80:80"
    volumes:
      - ./htdocs:/app
      - ./logs-apache:/var/log/apache2
    restart: always

    # не понимаю зачем    
    #links:
    #  - db

  db:
    image: mariadb
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database

    # тк идет внутреннее обращение по домену "db"
    # нужно лишь для внешного подключения к субд
    #ports:
    #  - "3306:3306"
