version: "2"
services:
  web:
    image: tutum/apache-php
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "80:80"
    volumes:
      - ./htdocs:/app
      - ./logs-apache:/var/log/apache2
    restart: always

    # не понимаю зачем    
    #links:
    #  - db

  db:
    image: mariadb
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database

    # порт по внешку нужен лишь для отладки
    ports:
     - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8800:80
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
